module.exports = {
  HTTP: {},
  ERROR_CODE: {
    INCORRECT_LOGIN_DATA: 'INCORRECT_LOGIN_DATA',
    ACCESS_DENIED: 'ACCESS_DENIED',
    INCORRECT_DATA: 'INCORRECT_DATA',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    NOT_EXIST: 'NOT_EXIST',
    INCORRECT_DATE_RANGE: 'INCORRECT_DATE_RANGE',
    ALREADY_EXIST: 'ALREADY_EXIST',
    CLOUDPAYMENTS_ERROR: 'CLOUDPAYMENTS_ERROR',
    NOTHING_TO_PAY: 'NOTHING_TO_PAY',
  },
};
