module.exports = {
  statuses: {
    INIT: 'INIT',
    PROCESSING: 'PROCESSING',
    COMPLETED: 'COMPLETED',
    FAIL: 'FAIL',
    REFUNDED: 'REFUNDED',
    REFUND_FAIL: 'REFUND_FAIL',
    PAYED: 'PAYED',
    ADD_CARD_FLOW: 'ADD_CARD_FLOW',
    ADD_CARD_FLOW_REFUND_PROCESSING: 'ADD_CARD_FLOW_REFUND_PROCESSING',
  },
};
